apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: cloud-provider
    app.kubernetes.io/name: harvester-cloud-provider
  name: harvester-cloud-provider
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: cloud-provider
      app.kubernetes.io/name: harvester-cloud-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cloud-provider
        app.kubernetes.io/name: harvester-cloud-provider
    spec:
      containers:
      - args:
        - --cloud-config=/etc/kubernetes/cloud-config/cloud-config.toml
        command:
        - harvester-cloud-provider
        image: rancher/harvester-cloud-provider:master-head
        imagePullPolicy: Always
        name: harvester-cloud-provider
        resources: {}
        volumeMounts:
        - mountPath: /etc/kubernetes/cloud-config
          name: cloud-config
      serviceAccountName: harvester-cloud-controller-manager
      tolerations:
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Equal
        value: "true"
      volumes:
        - name: cloud-config
          secret:
            secretName: cloud-config