#!/bin/bash
set -e

cd $(dirname $0)/..

# Prevent accidental imports/dependencies on harvester/harvester to reduce CVEs.
# Do not import it directly. If generated controllers/clients are needed,
# generate them directly in this repository instead.
echo "Checking dependencies in go.mod"
if grep -E 'github\.com/harvester/harvester([ /]|$)' go.mod; then
    echo "Error: direct dependency on github.com/harvester/harvester is not allowed in go.mod" >&2
    exit 1
else
    echo "PASS"
fi

if ! command -v golangci-lint; then
    echo "WARNING: Skipping validation: no golangci-lint available" >&2
    exit 0
fi

echo Running validation

echo Running: golangci-lint

# Command `RUN golangci-lint --version` on Dockerfile.dapper does not print anything
# It shows info like `golangci-lint has version 2.11.4 built with go1.26.1 from 8f3b0c7e on 2026-03-22T17:35:14Z` here
golangci-lint --version

golangci-lint run

echo Running: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
